stages:
  - build
  - deploy
  - clean_up

image: docker:git

cache:
  paths:
  - node_modules # This folder is cached between builds

build:
  stage: build
  image: node:latest
  script:
    - npm install --silent
    - npm test

push:
  stage: deploy
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t unwelch/backend:$CI_JOB_ID .
    #- docker tag unwelch/backend:$CI_JOB_ID registry.gitlab.com/unwelch/backend:$CI_JOB_ID
    - docker tag unwelch/backend:$CI_JOB_ID registry.gitlab.com/unwelch/backend:latest
    - docker push registry.gitlab.com/unwelch/backend:latest

clean_up_job:
  stage: clean_up
  script:
    - rm -rf node_modules
    - rm -rf ~/.node-gyp
  when: on_failure


stages:
  - build
  - deploy
  - clean_up

cache:
  paths:
  - node_modules # This folder is cached between builds

build:
  stage: build
  image: node:latest
  artifacts:
    untracked: true
  script:
    - npm install --silent
    - API_HOST=https://api.unwel.ch npm run build
    #- npm run test:e2e

push:
  stage: deploy
  image: docker:git
  dependencies:
    - build
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t unwelch/frontend:$CI_JOB_ID .
      #- docker tag unwelch/frontend:$CI_JOB_ID registry.gitlab.com/unwelch/frontend:$CI_JOB_ID
    - docker tag unwelch/frontend:$CI_JOB_ID registry.gitlab.com/unwelch/frontend:latest
    - docker push registry.gitlab.com/unwelch/frontend:latest

clean_up_job:
  stage: clean_up
  script:
    - rm -rf node_modules
    - rm -rf ~/.node-gyp
  when: on_failure
