language: node_js

node_js:
  - "10"

sudo: false
dist: trusty

addons:
  chrome: stable

services:
  - docker

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules
    - frontend/node_modules
    - backend/node_modules

git:
  depth: 3
  quiet: true

before_install:
  - "curl -o- -L https://yarnpkg.com/install.sh | bash"
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

install:
  - yarn
  - cd frontend
  - yarn
  - cd ..
  - cd backend
  - yarn
  - cp .env.dist .env
  - cd ..

after_install:
  - cd frontend
  - yarn test
  - cd ..
  - cd backend
  - yarn test
  - cd ..

script:
  - yarn start & export APP_PID=$!
  - sleep 60
  - yarn test:e2e
  - kill $APP_PID
  - killall node

before_deploy:
  - cd frontend
  - API_HOST=https://api.unwel.ch yarn run build
  - cd ..
  - cd backend
  - API_HOST=https://api.unwel.ch yarn run build
  - cd ..
  - docker build -t frontend ./frontend
  - docker tag frontend unwelch/frontend
  - docker build -t backend ./backend
  - docker tag backend unwelch/backend

deploy:
  provider: script
  on:
    branch: master
  script: sh deploy.sh
