language: node_js

node_js:
  - "10"

sudo: false
dist: trusty

addons:
  chrome: stable

services:
  - docker

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules

git:
  depth: 3
  quiet: true

env:
  global:
    - API_HOST='https://api.unwel.ch'

stages:
  - unit
  - e2e
  - deploy

jobs:
  include:
    - stage: unit
      env:
        matrix:
          - PACKAGE=frontend
          - PACKAGE=backend
      before_script:
        - "curl -o- -L https://yarnpkg.com/install.sh | bash"
        - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
      script:
        - cd $PACKAGE
        - yarn
        - yarn test
        - API_HOST=https://api.unwel.ch yarn run build
        - cd ..

    - stage: e2e
      before_script: yarn start & export APP_PID=$!
      script: yarn test:e2e
      after_script: kill $APP_PID

    - stage: deploy
      env:
        matrix:
          - PACKAGE=frontend
          - PACKAGE=backend
      before_script:
        - docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
        - docker build -t $PACKAGE ./$PACKAGE
        - docker tag $PACKAGE unwelch/$PACKAGE
      script: docker push unwelch/$PACKAGE
      on:
        branch: master
